name: Atmos with Dependencies
description: A GitHub Action that dynamically runs affected stacks and their dependencies.
author: Cloud Posse, LLC
inputs:
  levels:
    description: The number of levels of dependencies to include
    required: true
runs:
  using: composite
  steps:
    - name: generate
      shell: bash
      run: |
        mkdir -p ./.generated-dynamic-dependencies && cat <<'EOF' >./.generated-dynamic-dependencies/action.yml
          name: Plan Component1 and Dependencies
          runs:
            on: [workflow_call]
          jobs:
            component1:
              steps:
              - run: pwd
                shell: bash
              - name: Plan Component1
                id: step-1
                shell: bash
                run: echo "atmos terraform plan component1 --stack one"
              - name: Apply Component1
                id: step-2
                shell: bash
                run: echo "atmos terraform apply component1 --stack one"
            component2:
              need: component1
              steps:
              - run: pwd
                shell: bash
              - name: Plan Component2
                id: step-1
                shell: bash
                run: echo "atmos terraform plan component2 --stack one"
              - name: Apply Component2
                id: step-2
                shell: bash
                run: echo "atmos terraform apply component2 --stack one"
        EOF
