name: Atmos with Dependencies
description: A GitHub Action that dynamically runs affected stacks and their dependencies.
author: Cloud Posse, LLC
inputs:
  levels:
    description: The number of levels of dependencies to include
    required: true
runs:
  using: composite
  steps:
    - name: Setup
      shell: bash
      run: |
        mkdir -p ./.generated-dynamic-dependencies && cat <<'EOF' >./.generated-dynamic-dependencies/action.yml
        runs:
          using: composite
          steps:
          - run: pwd
            shell: bash
          - run: ls -la ./.generated-dynamic-dependencies
            shell: bash
          - name: Plan Component1
            id: step-1
            shell: bash
            run: echo "atmos terraform plan component1 --stack one"
          - name: Apply Component2
            id: step-2
            shell: bash
            run: echo "atmos terraform apply component1 --stack one"
          - name: Plan Component2
            id: step-3
            shell: bash
            run: echo "atmos terraform plan component2 --stack one"
          - name: Apply Component2
            id: step-4
            shell: bash
            run: echo "atmos terraform apply component2 --stack one"
        EOF
